name: Deploy App

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Package Dependencies
      run: npm ci

    - name: Generate Type Definitions for PrismaClient
      run: npx prisma generate

    - name: Lint Code
      run: npm run lint

    - name: Run Unit Tests
      run: npm run test

    - name: Run End-to-End Tests
      run: npm run test:e2e

  build:
    runs-on: ubuntu-latest
    needs: test

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Package Dependencies
      run: npm ci

    - name: Generate Type Definitions for PrismaClient
      run: npx prisma generate

    - name: Build the App
      run: npm run build

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nest-build
        path: dist/
        if-no-files-found: error
        retention-days: 90
    - name: Check Build Artifact Files
      run: ls -R dist/
